[tool.poetry]
name = "convert"
version = "0.1.3"
description = "Convert ebook to different formats"
authors = ["skip"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
